channels:
  - pytorch
  - defaults
  - nvidia
  - fastai
  - rapidsai
  - defaults
  - conda-forge
dependencies:
  ##########################
  # Generic configurations #
  ##########################
  #- nano
  #- git
  #--- github
  #- gh 
  ##--- Python
  - python=3.10
  - pip
  #- twine
  #- xeus-python
  ##--- NodeJS ¿Se usa en algún lado?
  - nodejs
  #---Jupyter
  #- ipywidgets
  - jupyterlab
  #- jupyterlab-git
  #- nbclassic>=0.2.8
  #- nbdev
  #--- passwords & files
  #- keyrings.alt
  #- platformdirs #=2.5.2=py310h06a4308_0

  ##############
  # CUDA & GPU #
  ##############
  - cuda-toolkit=12.2
  #- cudf
  #- cuml
  #- genv
  #--- Torch
  ############
  # Specific #
  ############
  - pytorch
  #---Graphs & imgs
  #- plotly
  #- jpeg
  #- seaborn
  #--- IA
  #- hdbscan
  #- imbalanced-learn>=0.8.0
  #- pyts>=0.12.0
  #- umap-learn
  #- scikit-learn=1.2.2
  #- wandb