channels:
  - nvidia/label/cuda-12.2.0
  - conda-forge
dependencies:
  ##########################
  # Generic configurations #
  ##########################
  - nano
  - git
  #--- github
  - gh 
  ##--- Python
  - python=3.10
  - pip
  - twine
  - xeus-python
  #---Jupyter
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - nbclassic>=0.2.8
  ##############
  # CUDA & GPU #
  ##############
  - nvidia/label/cuda-12.2.0::cuda-toolkit=12.2.0
  